spring:
  application:
    name: hrm-employee-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: BRF_SSD
    password: admin
    driverClassName:  oracle.jdbc.OracleDriver   
server:
  port: 8085
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8762/eureka/
    register-with-eureka: true
    fetch-registry: true