spring:
  application:
    name: hrm-employee-service
  datasource:
    url: jdbc:h2:mem:mydb
    username: dhani
    password: ds
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled : true
      path : /h2-ui
server:
  port: 8085
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8762/eureka/
    register-with-eureka: true
    fetch-registry: true